version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: stage_esprit
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  web:
    image: fatenk/stagedevops-back
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=db
volumes:
  db_data: