version: '3'
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: stage_esprit
      POSTGRES_USER: root
      POSTGRES_HOST_AUTH_METHOD: trust
  web:
    image: 